### ISSUE TITLE
UnknownDependencyException: WorldEdit

### ISSUE THREAD

**Issue by SuperColaTyphoon** [Plajer-Lair/BuildBattle#5]
## Issue name
UnknownDependencyException
### Sort description of issue
I dont know what this means
## Error code
```
[00:31:14] [Server thread/ERROR]: Could not load 'plugins/BuildBattle.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: WorldEdit
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.13.jar:git-Spigot-69774b3-3006dee]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.loadPlugins(CraftServer.java:314) [spigot-1.13.jar:git-Spigot-69774b3-3006dee]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:213) [spigot-1.13.jar:git-Spigot-69774b3-3006dee]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar:git-Spigot-69774b3-3006dee]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

## Additional info
- Spigot version: 1.13
- Plugin version: 3.4.0

**Comment by Plajer** [comment]
Let me introduce you - English.
English it's a language.

Now let me introduce you your problem:
**UnknownDependencyException: WorldEdit**

Now let's add some spaces and change some words to make it really simple.

**Unknown Dependency Exception: WorldEdit**

Now make it simplier using simplier words.

**I found an error, I don't have this required dependency: WorldEdit**

have fun.
